mybatis:
  # 数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/library?useSSL=false&serverTimezone=UTC
    username: root
    password: 0000
    hikari:
      maximum-pool-size: 10  # 设置最大连接池大小
      minimum-idle: 5         # 设置最小空闲连接数
      idle-timeout: 30000     # 设置空闲连接的超时时间
      connection-timeout: 30000  # 设置连接超时时间
      max-lifetime: 60000       # 设置连接的最大生命周期

  # 自动加载的映射文件
  mapper-locations: classpath:/com/book/dao/*.xml  # 扫描映射文件
  type-aliases-package: com.book.domain            # 扫描实体类包
  config-location: classpath:mybatis-config.xml    # MyBatis 配置文件位置

# 配置 Spring 事务
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/library?useSSL=false&serverTimezone=UTC
    username: root
    password: 0000
  transaction:
    management:
      enabled: true
